# Generated by Django 4.1.7 on 2023-03-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, unique=True, verbose_name='Ссылка')),
                ('reference', models.CharField(max_length=30, verbose_name='Ресурс')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Населенный пункт')),
                ('street', models.CharField(blank=True, max_length=500, null=True, verbose_name='Улица(адрес)')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Район')),
                ('microdistrict', models.CharField(blank=True, max_length=500, null=True, verbose_name='Микрорайон')),
                ('rooms_number', models.IntegerField(blank=True, null=True, verbose_name='Количество комнат')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('seller_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер продавца')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата объявления')),
                ('is_tg_posted', models.BooleanField(default=False, verbose_name='Размещено в ТГ')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архивное')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'db_table': 'flats',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, unique=True, verbose_name='Ссылка')),
                ('photo', models.BinaryField(verbose_name='Фото')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='realty_app.flats', verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'photos',
                'ordering': ('flat', 'id'),
            },
        ),
    ]
